//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparkHelp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SparkHelp_dbEntities : DbContext
    {
        public SparkHelp_dbEntities()
            : base("name=SparkHelp_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckedAnswer> CheckedAnswers { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<UncheckedAnswer> UncheckedAnswers { get; set; }
    }
}
